### ISSUE TITLE
wiki is broken

### ISSUE THREAD

**Issue by soundyogi** [xtremespb/taracotjs#2]
The wiki seems ot be broken

This Project is awesome, would you consider it ready for production? how could one help?

**Comment by xtremespb** [comment]
Thanks for report, the Wiki has been repaired. The DNS servers may require some time for an update.
I guess the project is currently in Beta stage, but I'm using it in production since several weeks, and it's working fine.

**Comment by soundyogi** [comment]
Thx! Cool, then ill see into it  and will contribute as much as I can :)

**Comment by soundyogi** [comment]
Is the wiki on github? I could help fix it, the links are broken:

Instead of:
https://wiki.taracot.org/doku.php?id=upgrade

The links point to:
https://wiki.taracot.org/doku.php/upgrade

:) cheers!

**Comment by xtremespb** [comment]
It's a Wiki on wiki.taracot.org. As I've moved from Apache to NGINX, I forgot to change the URL configuration. Now both links are functional. Thanks!
